// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SammBotNET.Database;

namespace SammBotNET.Migrations.EmotionalSupportDBMigrations
{
    [DbContext(typeof(EmotionalSupportDB))]
    partial class EmotionalSupportDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("SammBotNET.Database.EmotionalSupport", b =>
                {
                    b.Property<int>("SupportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupportMessage")
                        .HasColumnType("TEXT");

                    b.HasKey("SupportId");

                    b.ToTable("EmotionalSupport");
                });
#pragma warning restore 612, 618
        }
    }
}
