version: 2
updates:
  # For the bot itself.
  - package-ecosystem: "nuget"
    directory: "/Source/SammBot.Bot"
    schedule:
      interval: "daily"
    target-branch: "master"
    labels:
      - "dependencies"
      - "master"
      - "bot"
    assignees:
      - "analogfeelings"
    reviewers:
      - "analogfeelings"
    commit-message:
      prefix: "[Bot -> All]"
      include: "scope"
      
  # For the web generator.
  - package-ecosystem: "nuget"
    directory: "/Source/SammBot.WebGenerator"
    schedule:
      interval: "daily"
    target-branch: "master"
    labels:
      - "dependencies"
      - "master"
      - "web generator"
    assignees:
      - "analogfeelings"
    reviewers:
      - "analogfeelings"
    commit-message:
      prefix: "[WebGenerator -> All]"
      include: "scope"
