version: 2
updates:
  # For the bot itself.
  - package-ecosystem: "nuget"
    directory: "/Source/SammBot.Bot"
    schedule:
      interval: "daily"
    target-branch: "master"
    labels:
      - "dependencies"
      - "master"
      - "bot"
    assignees:
      - "analogfeelings"
    reviewers:
      - "analogfeelings"
    commit-message:
      prefix: "[Bot -> All]"
      include: "scope"
      
  # For the library.
  - package-ecosystem: "nuget"
    directory: "/Source/SammBot.Library"
    schedule:
      interval: "daily"
    target-branch: "master"
    labels:
      - "dependencies"
      - "master"
      - "library"
    assignees:
      - "analogfeelings"
    reviewers:
      - "analogfeelings"
    commit-message:
      prefix: "[Library -> All]"
      include: "scope"
      
  # For the tests.
  - package-ecosystem: "nuget"
    directory: "/Source/SammBot.Tests"
    schedule:
      interval: "daily"
    target-branch: "master"
    labels:
      - "dependencies"
      - "master"
      - "tests"
    assignees:
      - "analogfeelings"
    reviewers:
      - "analogfeelings"
    commit-message:
      prefix: "[Tests -> All]"
      include: "scope"
