// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SammBotNET.Database;

#nullable disable

namespace SammBotNET.Migrations.PronounsDBMigrations
{
    [DbContext(typeof(PronounsDB))]
    partial class PronounsDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("SammBotNET.Database.Pronoun", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DependentPossessive")
                        .HasColumnType("TEXT");

                    b.Property<string>("IndependentPossessive")
                        .HasColumnType("TEXT");

                    b.Property<string>("Object")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reflexive")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Pronouns");
                });
#pragma warning restore 612, 618
        }
    }
}
