// <auto-generated />
using SammBotNET.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SammBotNET.Migrations
{
    [DbContext(typeof(BlacklistedUsersDB))]
    [Migration("20210216083518_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("BaldiBotNET.Database.BlacklistedUser", b =>
                {
                    b.Property<ulong>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("banType")
                        .HasColumnType("TEXT");

                    b.HasKey("userID");

                    b.ToTable("BlacklistedUser");
                });
#pragma warning restore 612, 618
        }
    }
}
