// <auto-generated />
using SammBotNET.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SammBotNET.Migrations.PhrasesDBMigrations
{
    [DbContext(typeof(PhrasesDB))]
    partial class PhrasesDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("BaldiBotNET.Database.Phrase", b =>
                {
                    b.Property<string>("content")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("authorID")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("serverID")
                        .HasColumnType("INTEGER");

                    b.HasKey("content");

                    b.ToTable("Phrase");
                });
#pragma warning restore 612, 618
        }
    }
}
