// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SammBotNET.Database;

#nullable disable

namespace SammBotNET.Migrations
{
    [DbContext(typeof(BotDatabase))]
    partial class BotDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("SammBotNET.Database.PeoneImage", b =>
                {
                    b.Property<string>("TwitterUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("TwitterUrl");

                    b.ToTable("PeoneImages");
                });

            modelBuilder.Entity("SammBotNET.Database.Pronoun", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DependentPossessive")
                        .HasColumnType("TEXT");

                    b.Property<string>("IndependentPossessive")
                        .HasColumnType("TEXT");

                    b.Property<string>("Object")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReflexivePlural")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReflexiveSingular")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Pronouns");
                });

            modelBuilder.Entity("SammBotNET.Database.UserTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reply")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("ServerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserTags");
                });
#pragma warning restore 612, 618
        }
    }
}
