name: Run Unit Tests

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.cs'
      - '**.csproj'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.cs'
      - '**.csproj'
  workflow_dispatch:

jobs:
  run-unit-tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        dotnet-version: [ '8.0.x' ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.5

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Check Dependency Cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Install Dependencies
        run: dotnet restore
        
      - name: Build Tests
        run: dotnet build --configuration Release --no-restore
        
      - name: Run Tests
        run: dotnet test --no-restore --verbosity normal
